config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
      resources :users
      get '/users/result' => 'users#result'
      resources :services
      resources :from_languages
      resources :to_languages
      resources :documents
      resources :orders
      # get '/order' => 'orders#new'

      patch "/orders" => "orders#create"

      post "/search" => "pages#search", as: :search_translator #dont delete



   #login routes
    get '/login' => 'session#new' # login form
    post '/login' => 'session#create' # perform a login
    delete '/login' => 'session#destroy' # perform a log out

    # #service routes
    get '/service' => 'service#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id              :bigint(8)        not null, primary key
#  email           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Client < ApplicationRecord
  has_secure_password
validates :email, :presence => true, :uniqueness => true

    has_many :orders
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :bigint(8)        not null, primary key
#  category   :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Document < ApplicationRecord
  has_many :services

end

app/models/from_language.rb
# == Schema Information
#
# Table name: from_languages
#
#  id            :bigint(8)        not null, primary key
#  language_from :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class FromLanguage < ApplicationRecord
  has_many :services

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :bigint(8)        not null, primary key
#  user_id    :integer
#  client_id  :integer
#  service_id :integer
#  comment    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :client, :optional => true
  
  has_many :services, through: :users

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id               :bigint(8)        not null, primary key
#  title            :text
#  image            :text
#  price            :decimal(, )
#  user_id          :integer
#  time_frame_id    :integer
#  from_language_id :integer
#  to_language_id   :integer
#  document_id      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Service < ApplicationRecord
  belongs_to :user, :optional => true
  belongs_to :from_language, :optional => true
  belongs_to :to_language, :optional => true
  belongs_to :document, :optional => true
  belongs_to :time_frame, :optional => true

  has_many :orders, through: :users

  # validates_presence_of :title, :user_id

end

app/models/time_frame.rb
# == Schema Information
#
# Table name: time_frames
#
#  id         :bigint(8)        not null, primary key
#  urgercy    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TimeFrame < ApplicationRecord
  has_many :services
  
end

app/models/to_language.rb
# == Schema Information
#
# Table name: to_languages
#
#  id          :bigint(8)        not null, primary key
#  language_to :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ToLanguage < ApplicationRecord
  has_many :services
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :text
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  adm             :boolean
#  translator      :boolean
#

class User < ApplicationRecord
  has_secure_password
validates :email, :presence => true, :uniqueness => true
has_many :services
has_and_belongs_to_many :orders

include PgSearch
pg_search_scope :search_for, against: %i(email language_from)
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :get_languages, :only => [:home, :search]
  def home
  end

  def search
    from_id = params[:from_languages].to_i
    to_id = params[:to_languages].to_i

    # get reference to service schema
    arel = Service.arel_table

    # where service from_language_id == from_id && to_language_id == to_id
    query = arel[:from_language_id].eq(from_id).and(arel[:to_language_id].eq(to_id))

    @user_matches = User.joins(:services).distinct.where(query)

    # find Users where there is at least one service that has from_id and to_id
    # OLD VERSION
    # @user_matches = User.joins(:services)
    #                 .distinct.where(
    #                   services: {
    #                     :from_language_id => from_id,
    #                     :to_language_id => to_id
    #                   })

    render :action => :home
  end

  private
    def get_languages
      @users = User.all
      @from_languages = FromLanguage.all
      @to_languages = ToLanguage.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <title>Translatorss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

  </head>

  <body>
    <div class="coutainer">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a href="#" class="navbar-brand">
            <i class="fas fa-file fa-2x"></i>
          </a>
          <ul class="navbar-nav">
            <% if @current_user.present? %>
              <li class="nav-item"><%= link_to 'Home', root_path, :class => "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Logout', login_path, :class => "nav-link", data: {:confirm => 'Are you sure?'}, :method => :delete %>
              </li>
              <li class="nav-item"><%= link_to 'Create service', new_service_path, :class => "nav-link", :method => :get %></li>

              <li class="nav-item">  <%= link_to 'See service', services_path, :class => "nav-link", :method => :get %>

                <li class="nav-item">  <%= link_to 'New Order', new_order_path, :class => "nav-link", :method => :get %>

                  <li class="nav-item">  <%= link_to 'See Orders', orders_path, :class => "nav-link", :method => :get %>

              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Login', login_path, :class => "nav-link", data: {}, :method => :get %></li>

              <li class="nav-item">
                <%= link_to 'Sign up', new_user_path, :class => "nav-link", data: {}, :method => :get %></li>
            <% end %>
          </ul>
        </nav>


    </div>
    <%= yield %>
    <footer>
    <div class="container">
      <h6 class="display-8">© 2018 Translatorss PTY LTD</h6>
    </div>
  </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="card-body-fluid  mb-3">
    <h1 class="display-4">Translatorss</h1>

      <%= form_tag search_translator_path do %>
        <%= label_tag "Select your translator: "%>
        <%= select_tag "from_languages", options_for_select([["select a language from", -1]] + @from_languages.pluck(:language_from, :id)) %>

          <%= select_tag "to_languages", options_for_select([["select a language to", -1]] + @to_languages.pluck(:language_to, :id)) %>
      <%= submit_tag "submit" %>
      <% end %>

  <% unless @user_matches.nil? %>
    <div class="services">
    <% @user_matches.each do |user| %>
      <div>
        <%= link_to user.email, user_path(user) %>
      </div>
    <% end %>
    </div>
  <% end %>







</div>